---
title: '**HyDe program notes**'
output:
  html_document:
    highlight: tango
    theme: lumen
    toc: yes
    toc_depth: 1
date: '`r format(Sys.time(), "%d %B, %Y")`'
---

<style>
p {
  font-size: 125%;
}

li {
  font-size: 115%;
}
</style>

--------

# Including multiple individuals per taxon

To include multiple individuals

$$
N_{obs} = N_{OUT} \times N_{P1} \times N_{HYB} \times N_{P2} \times S
$$

$$
p_7 = \frac{X_{ijji}}{N_{obs}}, \\
p_9 = \frac{X_{ijij}}{N_{obs}}, \\
p_4 = \frac{X_{iijj}}{N_{obs}}. \\
$$

# Integrating over missing and/or ambiguous data

In phylogenetics it is common to encode missing or ambiguous DNA bases using IUPAC codes (e.g., Y = C or T, N/? = A or G or C or T, etc.). In the original version of HyDe these sites were ignored. However, we wanted to include these sites in the hybrid detection method if possible. To do this, we realized that we could integrate over missing or ambiguous data in forming the site count pattern matrix by weighting the counts for each possible site pattern that included an ambiguous site. For example, a site pattern of {A, A, G, Y} can be resolved as either {A, A, G, C} or {A, A, G, T}. Therefore, we add 0.5 to each of these patterns in the count matrix. In general, for a given site pattern, we consider all possible resolutions of ambiguity codes into the bases A, G, C, and T and then add a weight equal to 1 divided by the size of the set of resolutions to each resolved site pattern in the count matrix. We do this with the following constraints:

 - No gaps $\rightarrow$ Sites with gaps are ignored.
 - No more than two ambiguous bases per site pattern $\rightarrow$ the minimum weight is then equal to 1/16 (two taxa have missing data).
