---
title: '**HyDe: hybrid detection using phylogenetic invariants**'
output:
  html_document:
    highlight: tango
    theme: lumen
    toc: yes
    toc_depth: 1
date: '`r format(Sys.time(), "%d %B, %Y")`'
---
<style>
p {
  font-size: 125%;
}

li {
  font-size: 115%;
}
</style>

--------

The program HyDe implements the method for hybrid detection described in:

 - Laura S. Kubatko and Julia Chifman. An Invariants-based Method for Efficient Identification of Hybrid Species From Large-scale Genomic Data. *bioRxiv* **doi**: <a href="https://doi.org/10.1101/034348" target="_blank">https://doi.org/10.1101/034348</a>.
 
# Installation

HyDe is written in C++ and can be compiled into an executable (`hyde`) using the `Makefile` provided in the `src/` folder. 
Some of the features in HyDe use the C++11 standard, so a compatible compiler is required. There are a few different options for compiling the executable, but the simplest way is to download the HyDe source code, change into the `src/` directory and type `make`:

```bash
# Basic compilation and installation of hyde
cd HyDe/src
make
sudo make install
```

The last command will copy `hyde` to `/usr/local/bin` so that it is available for execution from anywhere on your computer. 
If you want to remove it, simply type `sudo make uninstall`.

### Multithreading using OpenMP

HyDe was written with the option to allow multithreading using the OpenMP library. OpenMP is included with the GNU g++ compilers by default, but Apple based C++ compilers no longer support OpenMP. One of the easiest ways to get GNU g++ on a Mac is to install it using Homebrew. The steps for compiling with OpenMP multithreading are almost the same as before but with one slight modification to the `make` command:

```bash
# Compiling with OpenMP, add OPENMP=yes to make step
cd HyDe/src
make OPENMP=yes
sudo make install
```

### Recompiling

If at any point you need to start the compilation process from scratch (e.g., you want to recompile with multithreading), type `make clean` in the `src/` directory. This will remove the `hyde` executable and C++ object files (`*.o`) so that everything can be recompiled in the way that you want.

# Command line interface

HyDe has a simple command line interface that allows users to run the program on their data by passing the relevant files and information using flags. 

### Getting help

```bash
hyde --help

## Usage: hyde -i <infile> -n <num-individuals> -s <num-sites> 
##        -m <species-map> -o <outgroup> [additional options]
##
## Information options:
##   -h [--help]          Prints this help message
##   -v [--version]       Prints version information
##
## Program options:
##   -i [--infile]        Name of the data input file
##   -n [--num-ind]       Number of individuals in data matrix
##   -s [--num-sites]     Number of sites in the data matrix
##   -t [--num-taxa]      Number of taxa (species, OTUs)
##   -m [--map]           Map of individuals to taxa
##   -o [--outgroup]      Name of the outgroup (only one accepted)
##
## Additional options:
##   -p [--p-value]       P-value cutoff for test of significance (default=0.05)
##   --threads            Number of threads to use for parallelization (default=1)
##   --prefix             Append a prefix to the beginning of outfile
```

### Version information

```bash
hyde --version

## This is HyDe version 0.1.0-alpha (February 2017).
```

# Getting started

The two most important files for running HyDe are the data input file and the map file. The data file is a simple text file that is similar to sequential Phylip format (each individual gets 1 line) but with the first row with the number of individuals and sites removed. There are virtually no restrictions on the length of individual names and they don't all have to be the same length. There does need to be some form of white space (e.g., tab delimited) separating the individual name from the DNA data. The map file is a two column file that maps individuals in the data file to their respective taxa. The individual names are in the first column and need to be in the same order as the data file. Taxon names are in the second column. They don't need to be the same length and only need to be separated from the individual names by white space. Make sure to organize the data and map so that all individuals within the same taxon occur sequentially. Examples of these files can be found in the `examples/` folder.

## Input file

```
Individual1    AGTCGTGCGAGTACAGTGTGAC...
Individual2    AGTCGCGCGAGTACAGTGTGAC...
.
.
.
IndividualN    AGTCGTGCGAGRACAGTGTGAC...
```

## Map file

```
Individual1 Taxon1
Individual2 Taxon1
.
.
.
IndividualN TaxonM
```

## Example analysis with *Sistrurus* rattlesnake data set

```bash
cd HyDe/examples
hyde --infile snake-data.txt \
     --map snake-map.txt \
     --num-ind 52 \
     --num-taxa 7 \
     --num-sites 8466 \
     --outgroup out \
     --prefix snake
```

For more details on the analysis carried out by HyDe, see the <a href="http://pblischak.github.io/HyDe/HyDe-notes.html" target="_blank">program notes</a>.